development:
  secret_key_base: 910dc035444bd31837794a42baca92fa28f1d8d13c8f3a15c955ecfdeccdbbfb8113efb0cd32c708d8712b7de63cfe6263ee76c62d8b9e5d5e5c3e5a1139eb36
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  email_server_address: <%= ENV["EMAIL_SERVER_ADDRESS"] %>
  email_port: <%= ENV["EMAIL_PORT"] %>
  email_domain: <%= ENV["EMAIL_DOMAIN"] %>
  email_user_name: <%= ENV["EMAIL_USER_NAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  broker_email: <%= ENV["BROKER_EMAIL"] %>
  registrant_mailer_default_from: <%= ENV["REGISTRANT_MAILER_DEFAULT_FROM"] %>
  mapbox_access_token: pk.eyJ1Ijoibm9lYXNzb2NpYXRlcyIsImEiOiJjaWlnenI0ZHQwMnBwdnRtMXJ5a3NnenFyIn0.NnqNQJlLgSViinCd6PWGnA

test:
  secret_key_base: 39cc6c4df52e3027e7e27664061914545f6f8e3119fe9de60df13c8ff67eb6b1e5f1ac4cc2393c2bb8df206675d4d63b6aa749a628dd6b50a37fc262129d06ac
  mapbox_access_token: pk.eyJ1Ijoibm9lYXNzb2NpYXRlcyIsImEiOiJjaWlnenI0ZHQwMnBwdnRtMXJ5a3NnenFyIn0.NnqNQJlLgSViinCd6PWGnA

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  email_server_address: <%= ENV["EMAIL_SERVER_ADDRESS"] %>
  email_port: <%= ENV["EMAIL_PORT"] %>
  email_domain: <%= ENV["EMAIL_DOMAIN"] %>
  email_user_name: <%= ENV["EMAIL_USER_NAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  broker_email: <%= ENV["BROKER_EMAIL"] %>
  registrant_mailer_default_from: <%= ENV["REGISTRANT_MAILER_DEFAULT_FROM"] %>
  mapbox_access_token: <%= ENV["MAPBOX_ACCESS_TOKEN"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV["GOOGLE_API_KEY"] %>
  email_server_address: <%= ENV["EMAIL_SERVER_ADDRESS"] %>
  email_port: <%= ENV["EMAIL_PORT"] %>
  email_domain: <%= ENV["EMAIL_DOMAIN"] %>
  email_user_name: <%= ENV["EMAIL_USER_NAME"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  broker_email: <%= ENV["BROKER_EMAIL"] %>
  registrant_mailer_default_from: <%= ENV["REGISTRANT_MAILER_DEFAULT_FROM"] %>
  mapbox_access_token: <%= ENV["MAPBOX_ACCESS_TOKEN"] %>
